var tileCodes = {
    "floor"                 : 1,
    "wall"                  : 2,
    "yellowDoor"            : 3,
    "yellowKey"             : 4,
    "start"                 : 5,
    "exit"                  : 6,

    "nascar"                : 7,
    "help"                  : 8,
    "ball"                  : 9,
    "predator"              : 10,
    "player2"               : 11,
    "coin"                  : 12,

    "toll"                  : 13,
    "tollGreen"             : 14,
    "pushBlock"             : 15,
    "redButton"             : 16,
    "dRedBlockInactive"     : 17,
    "dRedBlockActive"       : 18,

    "coinUncollected"       : 19,
    "water"                 : 20,
    "redDoor"               : 21,
    "redKey"                : 22,
    "aRedBlockInactive"     : 23,
    "aRedBlockActive"       : 24,

    "britishNascar"         : 25,
    "hiddenSwitch"          : 26,
    "smartCar"              : 27,
    "yellowButton"          : 28,
    "dYellowBlockInactive"  : 29,
    "dYellowBlockActive"    : 30,

    "constructionButton"    : 31,
    "help2"                 : 32,
    "cyanDoor"              : 33,
    "cyanKey"               : 34,
    "aYellowBlockInactive"  : 35,
    "aYellowBlockActive"    : 36,

    "teleporter1"           : 37,
    "teleporter2"           : 38,
    "teleporter3"           : 39,
    "greenButton"           : 40,
    "dGreenBlockInactive"   : 41,
    "dGreenBlockActive"     : 42,

    "outTeleporter"         : 43,
    "smartPredator"         : 44,
    "greenDoor"             : 45,
    "greenKey"              : 46,
    "aGreenBlockInactive"   : 47,
    "aGreenBlockActive"     : 48,

    "futureWall"            : 49,
    "futureFloor"           : 50,
    "brownButtonPressed"    : 51,
    "brownButtonUnpressed"  : 52,
    "brownBlockInactive"    : 53,
    "brownBlockActive"      : 54

};